# important element is REL_3_20_ISO in ref below
name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: vjcitn/isochk:0.0.7
# using r2u in 0.0.7
      env:
        NODE_ENV: development
      options: --cpus 2
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Assess R version
        run: (Rscript -e version)
      - name: show path to R
        run: (which R)
      - name: Where am I
        run: (pwd)
      - name: Checkout Repository 
        uses: actions/checkout@v4 
        with:
          ref: REL_3_20_ISO
      - name: What is here
        run: (ls)
      - name: view DESCRIPTION
        run: (cat DESCRIPTION)
      - name: get dependencies
        run: (Rscript -e "BiocManager::install(c(basename(getwd()), ref='RELEASE_3_20'), dependencies=TRUE, update=FALSE, Ncpus=2)")
      - name: look at pkgs
        run: (/usr/local/bin/Rscript -e 'print(sort(rownames(installed.packages())))')
      - name: do r cmd check
        run: (Rscript -e "rcmdcheck::rcmdcheck()")
