name: CI
on:
  push:
    branches: [ RELEASE_3_20 ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: vjcitn/isochk:0.0.6
      env:
        NODE_ENV: development
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Assess R version
        run: (Rscript -e version)
      - name: show path to R
        run: (which R)
      - name: Where am I
        run: (pwd)
      - name: Checkout Repository 
        uses: actions/checkout@v4 
        with:
          ref: RELEASE_3_20
      - name: What is here
        run: (ls)
      - name: view DESCRIPTION
        run: (cat DESCRIPTION)
      - name: get dependencies
        run: (Rscript -e "BiocManager::install(c(basename(getwd()), 'qpdf', 'rcmdcheck'), dependencies=TRUE, update=FALSE)")
      - name: Setup pandoc from r-lib
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.11' # The pandoc vers
      - name: look at pkgs
        run: (/usr/local/bin/Rscript -e 'print(sort(rownames(installed.packages())))')
      - name: do r cmd check
        run: (Rscript -e "rcmdcheck::rcmdcheck()")
